services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "8"
      DISK_SIZE: "100G"
      LANGUAGE: "English"
      REGION: "de-CH"
      KEYBOARD: "de-CH"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
    - /var/win:/storage
